INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (1, 1, 'Rose DeWitt Bukater');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (1, 2, 'Jack Dawson');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (2, 3, 'Cady Heron');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (2, 4, 'Regina George');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (2, 5, 'Gretchen Wieners');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (2, 6, 'Karen Smith');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (3, 7, 'Elizabeth Bennet');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (3, 8, 'Fitzwillian Darcy');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (4, 9, 'Anna Brady');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (4, 10, 'Declan O''Callaghan');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (5, 6, 'Sophie Hall');
INSERT INTO tb_act(movie_id, actor_id, actor_role) VALUES (5, 11, 'Charlie Wyman');